<?php

/**
 * للموظف الذي له دور RBAC: كل مسار admin.* يجب أن يطابق موردًا هنا،
 * ويملك المستخدم واحدة على الأقل من الصلاحيات المذكورة (أسماء جدول permissions حرفيًا).
 *
 * المفتاح = الجزء الثاني من اسم المسار بعد admin. (مثال: admin.advanced-courses.index → advanced-courses)
 * القيمة false = ممنوع لموظف RBAC (مثل أقسام خاصة بالسوبر أدمن فقط).
 */
return [
    'by_resource' => [
        'about' => ['manage.about-page'],
        'academic-subjects' => ['manage.courses', 'manage.academic-subjects', 'manage.academic-years'],
        'academic-supervision' => ['academic_supervision.manage'],
        'academic-years' => ['manage.courses', 'manage.academic-years', 'manage.academic-subjects'],
        'accounting' => ['manage.invoices', 'manage.payments', 'manage.transactions', 'view.financial-reports', 'manage.instructor-accounts', 'view.wallets', 'manage.wallets'],
        'achievements' => ['manage.achievements'],
        'activity-log' => ['view.activity-log'],
        'teacher-tools' => ['manage.courses', 'manage.packages'],
        'learning-paths' => ['manage.courses'],
        'agreements' => ['manage.agreements'],
        'assignments' => ['manage.assignments'],
        'attendance' => ['manage.attendance'],
        'badges' => ['manage.badges'],
        'certificates' => ['manage.certificates'],
        'classroom-recordings' => ['manage.live-sessions'],
        'consultations' => ['manage.consultations'],
        'institutions' => ['manage.packages', 'manage.institutions'],
        'institution-programs' => ['manage.packages', 'manage.institutions'],
        'institution-program-participants' => ['manage.packages', 'manage.institutions'],
        'contact-messages' => ['manage.contact-messages'],
        'inquiries' => ['manage.contact-messages'],
        'notification-center' => ['manage.notifications', 'manage.system-settings'],
        'free-trial-bookings' => ['manage.free-trial-bookings'],
        'coupons' => ['manage.coupons'],
        'course-categories' => ['manage.courses'],
        'courses' => ['manage.courses', 'manage.lectures'],
        'coupon-commissions' => ['manage.coupons', 'manage.expenses'],
        'dashboard' => ['admin.access', 'view.dashboard'],
        'email-broadcasts' => ['manage.email-broadcasts'],
        'employee-agreements' => ['manage.employee-agreements'],
        'employee-jobs' => ['manage.users'],
        'employee-notifications' => ['manage.notifications'],
        'employee-tasks' => ['manage.tasks'],
        'employees' => ['manage.users'],
        'exams' => ['manage.exams'],
        'expenses' => ['manage.expenses'],
        'faq' => ['manage.faq'],
        'installment-agreements' => ['manage.installments'],
        'installment-plans' => ['manage.installments'],
        'instructor-requests' => ['manage.instructor-requests'],
        'invoices' => ['manage.invoices'],
        'installments' => ['manage.installments'],
        'leads' => ['manage.leads'],
        'crm' => ['manage.leads'],
        'leaves' => ['manage.leaves'],
        'lectures' => ['manage.lectures'],
        'live-recordings' => ['manage.live-sessions'],
        'live-servers' => ['manage.live-servers'],
        'live-settings' => ['manage.live-servers'],
        'live-sessions' => ['manage.live-sessions'],
        'messages' => ['manage.messages'],
        'notifications' => ['manage.notifications'],
        'online-enrollments' => ['manage.enrollments'],
        'orders' => ['manage.orders'],
        'packages' => ['manage.packages'],
        'service-packages' => ['manage.packages'],
        'service-package-pricing-rules' => ['manage.packages'],
        'student-entitlements' => ['manage.packages', 'manage.tutoring-groups', 'manage.users'],
        'payments' => ['manage.payments'],
        'performance' => ['manage.performance'],
        'permissions' => ['manage.permissions', 'users.permissions'],
        'personal-branding' => ['manage.personal-branding'],
        'popup-ads' => ['manage.popup-ads'],
        'profile' => ['admin.access', 'view.dashboard'],
        'question-bank' => ['manage.question-bank'],
        'question-categories' => ['manage.question-bank'],
        'quality-control' => ['manage.quality-control', 'manage.student-control'],
        'referral-programs' => ['manage.referrals'],
        'referrals' => ['manage.referrals'],
        'reports' => ['view.reports', 'view.financial-reports', 'view.academic-reports'],
        'reviews' => ['manage.reviews'],
        'roles' => ['manage.roles', 'users.permissions'],
        'salaries' => ['manage.salaries'],
        'sales' => ['manage.leads', 'view.sales-analytics', 'manage.orders'],
        'site-services' => ['manage.site-services'],
        'site-testimonials' => ['manage.site-testimonials', 'manage.site-services'],
        'statistics' => ['view.statistics'],
        'subjects' => ['manage.courses', 'manage.academic-subjects'],
        'students-accounts' => ['manage.students-accounts', 'manage.users'],
        'support-inquiry-categories' => ['manage.support-tickets'],
        'support-tickets' => ['manage.support-tickets'],
        'system-settings' => ['manage.system-settings'],
        'payment-gateways' => ['manage.system-settings'],
        'tasks' => ['manage.tasks', 'view.tasks'],
        'tutoring-groups' => ['manage.tutoring-groups'],
        'tutoring-group-bookings' => ['manage.tutoring-groups'],
        'tutor-work-schedules' => ['manage.tutoring-groups'],
        'tutor-applications' => ['manage.users', 'manage.personal-branding', 'manage.contact-messages'],
        'hiring-form' => ['manage.users', 'manage.personal-branding', 'manage.contact-messages'],
        'one-to-one-sessions' => ['manage.tutoring-groups', 'manage.courses'],
        'transactions' => ['manage.transactions'],
        'two-factor-logs' => ['manage.two-factor-logs'],
        'user-permissions' => ['manage.user-permissions', 'users.permissions'],
        'users' => ['manage.users'],
        'video-providers' => ['manage.video-providers'],
        'wallets' => ['manage.wallets', 'view.wallets'],
        'withdrawals' => ['manage.withdrawals'],
    ],

    /**
     * مطابقة كاملة لاسم المسار (قبل lookup بالمورد)
     */
    'exacts' => [
        'admin.api.nav-notifications' => ['admin.access', 'view.dashboard', 'manage.notifications'],
    ],

    /**
     * بعد تسجيل الدخول: أول مسار admin يُفتح إن وُجدت الصلاحية (بالترتيب)
     */
    'post_login_admin_routes' => [
        ['permission' => 'admin.access', 'route' => 'admin.dashboard'],
        ['permission' => 'view.dashboard', 'route' => 'admin.dashboard'],
        ['permission' => 'manage.courses', 'route' => 'admin.advanced-courses.index'],
        ['permission' => 'manage.users', 'route' => 'admin.users.index'],
        ['permission' => 'manage.students-accounts', 'route' => 'admin.students-accounts.index'],
        ['permission' => 'manage.orders', 'route' => 'admin.orders.index'],
        ['permission' => 'manage.invoices', 'route' => 'admin.invoices.index'],
        ['permission' => 'manage.notifications', 'route' => 'admin.notifications.inbox'],
        ['permission' => 'manage.tasks', 'route' => 'admin.tasks.index'],
        ['permission' => 'view.tasks', 'route' => 'admin.tasks.index'],
        ['permission' => 'view.wallets', 'route' => 'admin.wallets.index'],
        ['permission' => 'manage.enrollments', 'route' => 'admin.online-enrollments.index'],
        ['permission' => 'view.statistics', 'route' => 'admin.statistics.index'],
        ['permission' => 'view.reports', 'route' => 'admin.reports.index'],
    ],
];
